#!/bin/bash
#SBATCH -A C3SE2020-1-8
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -o out.txt
#SBATCH -t 7-00:00:00
#SBATCH --mail-user=luho@chalmers.se
#SBATCH --mail-type=end
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8757_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2252_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1662_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2744_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3947_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5364_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1245_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2665_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8458_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2216_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15141_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2297_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2069_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3147_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4066_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16314_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1878_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4581_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5320_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3773_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6676_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7096_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6456_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1875_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5522_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4830_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12969_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3110_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4565_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4756_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3942_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3374_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2816_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7449_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1412_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3699_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5094_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2549_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5844_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2241_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4548_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7903_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1980_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2587_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5162_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9151_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9903_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2312_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4289_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5617_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11987_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6199_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2290_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4430_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3247_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3402_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2849_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4038_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3959_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4277_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1181_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5719_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14579_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15393_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1686_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3581_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4856_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11981_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5335_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10524_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3077_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11897_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7835_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8979_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9821_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4249_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6326_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2186_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10206_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1999_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2764_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3250_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1705_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16359_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6643_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9774_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2949_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4348_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6965_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1449_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2417_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4485_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15653_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9523_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2096_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2887_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2627_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9195_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2070_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3796_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3167_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3180_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3681_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14630_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1639_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10064_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9418_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1115_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16780_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8057_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6304_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1809_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3293_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7620_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1174_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1431_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2783_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4115_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2369_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2404_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1582_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1133_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9286_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12450_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9014_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4779_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2714_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4244_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2532_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4643_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3096_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5435_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4135_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2596_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15364_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5028_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4459_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4297_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2361_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8007_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6455_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6219_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4040_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5872_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13175_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1888_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2082_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15220_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5509_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1524_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17148_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4728_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9881_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2047_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2141_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8208_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10556_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9904_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4693_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4752_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11313_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3904_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2825_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2071_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3313_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3658_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3295_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5534_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2086_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1378_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4068_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5056_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4220_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11410_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2616_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15153_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6431_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7260_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9020_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1846_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2832_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1825_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1300_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4574_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13248_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7900_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7540_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13594_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5165_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6604_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1936_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1345_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2920_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13483_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15918_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12753_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4923_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1626_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5179_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15906_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9429_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4087_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9840_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12131_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3461_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4765_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9185_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1695_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5648_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6997_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15645_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10890_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1288_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5667_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16180_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3438_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6278_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4144_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7618_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8551_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10612_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2591_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3554_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3264_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4346_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1460_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9595_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5310_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11284_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16121_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12760_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12765_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1188_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7815_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11518_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5284_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6653_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14712_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5500_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3788_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5568_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7241_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6065_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4352_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4814_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4292_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4143_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10215_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9537_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2263_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7790_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6819_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6846_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12540_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4621_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7879_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6787_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13392_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9910_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5159_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16839_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2918_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3392_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1553_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6699_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3642_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12279_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2791_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3457_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4585_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2206_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2339_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2653_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3231_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6517_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1389_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1586_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6964_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3137_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11935_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11760_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3260_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2721_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2784_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5017_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5048_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14386_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2548_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7271_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9411_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11879_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4229_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9641_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4759_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16292_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2963_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3389_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7584_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16979_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7052_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2829_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7105_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3974_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1263_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8278_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6315_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3491_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1414_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12698_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3557_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7138_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10088_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2371_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6505_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3177_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6991_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1546_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1912_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4228_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8203_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2156_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12304_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15248_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11595_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1172_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12629_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11135_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2759_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1743_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14103_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5027_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3943_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3631_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1805_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4818_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3194_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3417_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14824_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1309_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2145_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4518_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1810_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5399_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14190_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2370_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4556_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3946_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18250_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9974_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2954_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10606_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6955_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3019_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4764_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2765_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2581_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1870_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1802_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1325_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6909_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4505_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6348_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9039_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5324_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14899_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3792_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8385_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4375_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3745_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9213_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3824_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7635_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13874_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12937_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5544_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4515_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1528_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18395_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1753_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3956_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2614_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6934_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3786_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4043_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12067_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13649_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10901_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16316_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5077_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3748_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2161_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5589_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13585_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7550_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5991_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6259_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5466_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3850_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10625_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2155_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2984_aa_aligned_test.bf & 
wait
