#!/bin/bash
#SBATCH -A C3SE2020-1-8
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -o out.txt
#SBATCH -t 7-00:00:00
#SBATCH --mail-user=luho@chalmers.se
#SBATCH --mail-type=end
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4891_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2452_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12744_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4568_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2367_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7967_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3410_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1495_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4512_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1927_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6513_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8683_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4635_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4613_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3403_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4529_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2287_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9640_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4362_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4872_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4265_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6670_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14687_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2246_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2699_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1319_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8530_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15968_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8433_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3797_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13541_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1387_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3053_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2392_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1821_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1678_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3086_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4500_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13604_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2092_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6026_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1228_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5720_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3595_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2454_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1979_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3702_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13950_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4254_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16759_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7910_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1493_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4208_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1618_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4283_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2001_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2647_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12865_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10240_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3546_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2525_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16855_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18005_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10205_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2981_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4530_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5647_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3352_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1935_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2195_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15622_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2873_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2226_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4439_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2904_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13352_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3329_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5468_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1295_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5097_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13138_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3538_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8068_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1547_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2119_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8131_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15769_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4997_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3192_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2919_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15279_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3560_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3237_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15741_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1776_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4190_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5198_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1462_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8957_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14622_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9219_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2956_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1278_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2225_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8429_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2889_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3967_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2982_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10879_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7677_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4191_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8631_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5793_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6977_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3456_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2708_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3698_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2884_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5899_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1443_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13579_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2900_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3172_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3891_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1839_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2354_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8908_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10720_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4560_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13073_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6631_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4944_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7691_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4146_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5527_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4888_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4364_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1290_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2285_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2580_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2833_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2010_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2279_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4025_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3620_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16774_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1896_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14635_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5200_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6974_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1336_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6990_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2188_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14461_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1925_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2831_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1476_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12497_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18004_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1641_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8911_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10975_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1957_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17584_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7485_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6978_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17145_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1099_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13804_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1702_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1994_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1851_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10449_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6022_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4969_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2739_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2588_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10617_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2684_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2975_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8621_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8028_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3751_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5314_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1818_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2033_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7706_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4330_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2620_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13086_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11629_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7253_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2894_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3453_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11136_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4065_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5273_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4181_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2170_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3860_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1562_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3612_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3135_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3394_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1874_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5835_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3950_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3899_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5421_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2222_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16402_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4577_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3727_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1960_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8104_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3379_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5444_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8827_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2810_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4325_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8326_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10104_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3082_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1983_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3511_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6374_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13246_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7813_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4571_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1408_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6367_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5434_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17668_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3621_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4248_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1416_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1892_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7909_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1459_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5098_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12249_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3962_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7289_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2265_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5313_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15513_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6048_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3395_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2583_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3094_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2635_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3611_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7830_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2844_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12145_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9042_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3049_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1746_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4417_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2838_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5428_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1362_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2874_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4652_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4842_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3777_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1550_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3726_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17799_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8359_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7854_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16669_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3889_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11719_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1620_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8213_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14914_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3466_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3279_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1714_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1866_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13799_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6622_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2017_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3373_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4782_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3356_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2522_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1437_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8164_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3124_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3826_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4178_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6536_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3567_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7128_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16015_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4486_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10932_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7352_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2329_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1883_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9161_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2016_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5385_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11175_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7418_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14904_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12661_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7521_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11920_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3517_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4746_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1531_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2773_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2444_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6416_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2035_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5406_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3113_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2348_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7187_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7000_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6265_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4812_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14087_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3846_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7737_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4094_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10712_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10131_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8566_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14341_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5577_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4302_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4700_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6698_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4218_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3259_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3010_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11705_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4754_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1623_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6360_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17410_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6685_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3363_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2073_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3893_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4650_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16959_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5118_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2113_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10628_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2664_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5160_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1334_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4696_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3493_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5045_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8881_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14831_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2321_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6174_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1978_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2527_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1324_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12672_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2300_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2681_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3228_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9822_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4158_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13998_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6299_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16838_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2504_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13155_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5662_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2451_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2421_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7435_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4751_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6062_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14388_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2221_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2177_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14348_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17031_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17256_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1638_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1687_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7062_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8370_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6396_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12844_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3607_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2608_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4138_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3296_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2550_aa_aligned_test.bf & 
wait
