#!/bin/bash
#SBATCH -A C3SE2020-1-8
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -o out.txt
#SBATCH -t 7-00:00:00
#SBATCH --mail-user=luho@chalmers.se
#SBATCH --mail-type=end
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8460_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13688_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12275_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3168_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5982_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13671_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4267_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4651_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3803_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3590_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4219_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11786_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18256_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2511_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13802_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3459_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16536_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15963_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14383_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2528_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5234_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9455_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10746_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1747_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7659_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5995_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6641_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3957_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2192_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4012_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4109_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3922_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5021_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1302_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6707_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4532_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10676_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6438_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4091_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1384_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1850_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9027_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7902_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1065_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9549_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3700_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3134_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6020_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7893_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1035_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2817_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2625_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5116_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4358_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2260_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3876_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18631_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8485_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6989_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3690_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7479_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6450_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16406_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4528_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13654_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9567_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3347_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13172_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2545_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4934_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12864_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16347_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8630_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3044_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1510_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2457_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1917_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15321_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4883_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5777_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2134_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7791_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9293_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3227_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5548_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9739_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3462_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3051_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5675_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17253_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3823_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4195_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4947_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7799_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5024_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16203_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4809_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1317_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1560_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9461_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8706_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1673_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3002_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2896_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1765_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6075_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6797_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6601_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3925_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4534_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6364_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10794_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5002_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5126_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7928_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3776_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4491_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17610_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16977_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1400_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13146_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2493_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4551_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4440_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9584_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11753_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2538_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4416_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5898_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1843_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1254_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16588_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7488_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2500_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15460_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12904_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2716_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5660_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5996_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7809_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5587_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3650_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4225_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1201_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2410_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4382_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2991_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2345_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14649_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4996_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9307_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2293_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15425_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11988_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2476_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9920_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7031_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5655_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12203_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7399_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12259_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3692_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2553_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7965_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4163_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11189_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17459_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4503_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2207_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5713_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5958_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4837_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16198_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1360_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2559_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15697_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5960_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4525_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3291_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3398_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3784_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5630_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2169_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1421_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4708_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16785_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5558_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4833_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5837_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5220_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4688_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8565_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4794_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3305_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3768_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4243_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8487_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3655_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2217_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8169_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15952_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3484_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4594_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1867_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15554_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7679_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3930_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3867_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4349_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2941_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9911_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3598_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6759_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8086_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8190_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2593_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4422_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5700_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3545_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2502_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2745_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4806_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6071_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8666_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10552_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3754_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3592_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1785_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8032_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4357_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5372_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6980_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2747_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5923_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1473_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3289_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8290_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1729_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17327_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14804_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11125_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15961_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3280_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5127_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5338_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14568_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4800_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4004_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6972_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7244_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14387_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7137_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1842_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10244_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1976_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14339_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6260_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2517_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14231_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2789_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5382_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3364_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2652_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3993_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4666_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8873_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3314_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3871_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3969_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2333_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3095_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3821_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1882_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2709_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7136_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2806_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6445_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6580_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12440_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9747_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6492_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18560_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3116_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5930_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4640_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13911_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1454_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7339_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3646_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2572_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4493_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4922_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2275_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3609_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3160_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3088_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5426_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13695_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14222_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2564_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13015_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2927_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1955_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4579_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2305_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3039_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2640_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3673_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3715_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9761_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13820_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1901_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4869_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4133_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4307_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15305_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17655_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5296_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2859_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9714_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3181_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10351_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1339_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG18247_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7080_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5830_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3809_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7408_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3870_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9230_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3472_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2214_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2584_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4481_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1197_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1209_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1448_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8257_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10913_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2187_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1643_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1886_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2091_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11734_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4156_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15128_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4363_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG16383_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1864_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6079_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6189_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5081_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6711_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2094_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2324_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2544_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11936_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13828_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2211_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3603_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3778_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2556_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3335_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1529_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1758_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5229_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2465_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1224_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG17946_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6742_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4607_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7948_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2356_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3330_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10629_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9412_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4031_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3998_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2012_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3749_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5166_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4174_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4900_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG11116_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7765_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG10648_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2244_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG2756_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG9798_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4730_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3571_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4712_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3115_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3787_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3906_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15406_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG12659_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG13593_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1296_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5530_aa_aligned_test.bf & 
wait
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG14086_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG6203_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1230_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3354_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5560_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4013_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3564_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5658_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3584_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4213_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5013_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3207_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4614_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG1415_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG3035_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG4272_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG5014_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG15650_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG8490_aa_aligned_test.bf & 
hyphy /cephyr/users/luho/Hebbe/evolution_analysis/hyphy_model/leisr_bf/OG7039_aa_aligned_test.bf & 
wait
